### PR TITLE
Create deploy.sh

### PR DESCRIPTION
**Pull request by Kvngsvnly**
Hello team,
 please review the changes and merge.
Thanks

### CODE REVIEW

**Comment by Ayowendi** [comment]
Will do boss

**Comment by Kvngsvnly** [comment]
wow, you deserve a raise

**Comment by Ayowendi** [comment]
It is Ayo and I boss. Not me and Ayo. Please update thanks

**Comment by Kvngsvnly** [comment]
you are fired!!!!

**Pull request merged**
